
package UI.ManurerAdminRole;

import UI.AdministrativeRole.*;
import Model.Emp.Emp;
import Model.Enterprise.Enterprise;
import Model.Organization.Organization;
import Model.Role.Role;
import Model.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @Author Deshna, Dhir, Prasad, Anisha
 */
public class MAdministerUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MAdministerUserAccountJPanel
     */
    private JPanel container;
    private Enterprise enterprise;

    public MAdministerUserAccountJPanel(JPanel container, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        this.container = container;

        popOrganizationComboBox();
        popData();
    }

    public void popOrganizationComboBox() {
        orgJComb.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
               /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
            orgJComb.addItem(organization);
        }
    }
    
       /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
    
    public void populateEmployeeComboBox(Organization organization){
        empJCombo.removeAllItems();
        
        for (Emp employee : organization.getEmpDir().getEmployeeList()){
            empJCombo.addItem(employee);
        }
    }
    
       /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
    
    private void populateRoleComboBox(Organization organization){
        roleJComboBox.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            roleJComboBox.addItem(role);
        }
    }
       /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/

    public void popData() {

        DefaultTableModel model = (DefaultTableModel) usernameTable.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : organization.getUserAccountDir().getUserAccountList()) {
                
                   /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) usernameTable.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenwquBar1sa = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        crteUser = new javax.swing.JButton();
        nameJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usernameTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        passwordJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        empJCombo = new javax.swing.JComboBox();
        bsacksdajButton1 = new javax.swing.JButton();
        jLsaabel512 = new javax.swing.JLabel();
        orgJComb = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        roleJComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenwquBar1sa.add(jMenu1);

        jMenu2.setText("Edit");
        jMenwquBar1sa.add(jMenu2);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crteUser.setBackground(new java.awt.Color(255, 102, 102));
        crteUser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        crteUser.setText("Create User Acccount");
        crteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crteUserActionPerformed(evt);
            }
        });
        add(crteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, 60));

        nameJTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 310, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("User Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 150, -1));

        usernameTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        usernameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(usernameTable);
        if (usernameTable.getColumnModel().getColumnCount() > 0) {
            usernameTable.getColumnModel().getColumn(0).setResizable(false);
            usernameTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 599, 206));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 135, -1));

        passwordJTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 310, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Employee");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 135, -1));

        empJCombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        empJCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empJComboActionPerformed(evt);
            }
        });
        add(empJCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 313, 30));

        bsacksdajButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bsacksdajButton1.setText(" Back");
        bsacksdajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsacksdajButton1ActionPerformed(evt);
            }
        });
        add(bsacksdajButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jLsaabel512.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLsaabel512.setText("Organization");
        add(jLsaabel512, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        orgJComb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        orgJComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgJCombActionPerformed(evt);
            }
        });
        add(orgJComb, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 313, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Role");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 135, -1));

        roleJComboBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(roleJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 313, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Manage User Accounts");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 9, 390, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ModelManurerAdminRole.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -100, 1000, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void crteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crteUserActionPerformed
        if (nameJTextField.getText().equals("")|| passwordJTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Username/Password is empty");
        }
        else
               /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
        {
        String uName = nameJTextField.getText();
        if (validatePassword(passwordJTextField.getText()))
        {
          String pwd = passwordJTextField.getText();
        Organization org232 = (Organization) orgJComb.getSelectedItem();
        Emp emp232 = (Emp) empJCombo.getSelectedItem();
        Role role = (Role) roleJComboBox.getSelectedItem();
        
           /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
        
        org232.getUserAccountDir().createUserAccount(uName, pwd, emp232, role);
        
        popData();
        
        }
        else {
            
               /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
            JOptionPane.showMessageDialog(null, "Kindly enter a valid alphanumeric password of 7 to 15 length");
        }
        }
      
        nameJTextField.setText("");
        passwordJTextField.setText("");
    }//GEN-LAST:event_crteUserActionPerformed

    private void bsacksdajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsacksdajButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_bsacksdajButton1ActionPerformed

    private void orgJCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgJCombActionPerformed
        Organization org245 = (Organization) orgJComb.getSelectedItem();
        if (org245 != null){
            populateEmployeeComboBox(org245);
            
               /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
            populateRoleComboBox(org245);
        }
    }//GEN-LAST:event_orgJCombActionPerformed

    private void empJComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empJComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empJComboActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bsacksdajButton1;
    private javax.swing.JButton crteUser;
    private javax.swing.JComboBox empJCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLsaabel512;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenwquBar1sa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox orgJComb;
    private javax.swing.JTextField passwordJTextField;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JTable usernameTable;
    // End of variables declaration//GEN-END:variables

    private boolean validatePassword(String text) {
        boolean flg2 = false;
        Pattern patt = Pattern.compile("^[a-zA-Z]\\w{7,15}$");    
        Matcher matt = patt.matcher(text);        
        if (!matt.matches())
        {             
            JOptionPane.showMessageDialog(null, "Password is invalid"); 
            flg2 = false;
        }  
        else{flg2 = true;}
        return flg2;   
    }
}