
package UI.DistributorRole;

import Model.EcoSys;
import Model.Enterprise.Enterprise;
import Model.Enterprise.ProducerEnt;
import Model.Organization.*;
import Model.UserAccount.UserAccount;
import Model.WorkQueue.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static UI.ManurerWHRole.ManurerWHJPanel.flg;

/**
 *
 * @Author Deshna, Dhir, Prasad, Anisha
 */
public class DistributorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private OrgProducerDistributor organization;
    private ProducerEnt enterprise;
    private UserAccount userAccount;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private EcoSys business;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DistributorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, OrgProducerDistributor organization, Enterprise enterprise,EcoSys business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = (ProducerEnt)enterprise;
        this.userAccount = account;
        this.business = business;
        valLbl.setText(enterprise.getName());
        populateSuppRequestTable();
      
        if (flg ==true)
        {
            FrwdFarmerBTN.setEnabled(true);
            FrwdToWarehouseBRN.setEnabled(false);
            flg= false;
        }
    }


    public void populateSuppRequestTable(){
     DefaultTableModel model = (DefaultTableModel)workRequestRMJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getSender().getEmp().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmp().getName();
            row[3] = request.getStatus();
            row[4] = request.getPrimItemQty();
            
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestRMJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        FrwdFarmerBTN = new javax.swing.JButton();
        FrwdToWarehouseBRN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 127, 30));

        valLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(valLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 208, 30));

        workRequestRMJTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        workRequestRMJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Raw Material Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestRMJTable);
        if (workRequestRMJTable.getColumnModel().getColumnCount() > 0) {
            workRequestRMJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestRMJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestRMJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestRMJTable.getColumnModel().getColumn(3).setResizable(false);
            workRequestRMJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 709, 96));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Raw Material Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        FrwdFarmerBTN.setBackground(new java.awt.Color(0, 255, 204));
        FrwdFarmerBTN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FrwdFarmerBTN.setText("Send to Producer");
        FrwdFarmerBTN.setEnabled(false);
        FrwdFarmerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrwdFarmerBTNActionPerformed(evt);
            }
        });
        add(FrwdFarmerBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 260, 50));

        FrwdToWarehouseBRN.setBackground(new java.awt.Color(0, 255, 204));
        FrwdToWarehouseBRN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FrwdToWarehouseBRN.setText("Send to Warehouse Manager");
        FrwdToWarehouseBRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrwdToWarehouseBRNActionPerformed(evt);
            }
        });
        add(FrwdToWarehouseBRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 300, 50));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Distributor");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 300, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UIDistributorRole.JPG"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 980, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void FrwdFarmerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrwdFarmerBTNActionPerformed
        // TODO add your handling code here:
        int scltRecord = workRequestRMJTable.getSelectedRow();
        
        if (scltRecord < 0){
            JOptionPane.showMessageDialog(null,"Kindly select a row before proceeding");
        }
        
        YieldRequest request = (YieldRequest)workRequestRMJTable.getValueAt(scltRecord, 0);
        request.setStatus("Forwarded to Producer ");
        populateSuppRequestTable();
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        
        Organization org = null;
        for (Organization org23 : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (org23 instanceof OrgProduction){
                org = org23;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
        }
        
    }//GEN-LAST:event_FrwdFarmerBTNActionPerformed

    private void sendToSupplierJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToSupplierJButtonActionPerformed
        int scltRecprd1 = workRequestRMJTable.getSelectedRow();
        
        if (scltRecprd1 < 0){
            return;
        }
        
        YieldRequest request = (YieldRequest)workRequestRMJTable.getValueAt(scltRecprd1, 0);
        request.setStatus("Forwarded to Manufacturer.Supplier ");
        populateSuppRequestTable();
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        
        Organization org = null;
        for (Organization org65 : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (org65 instanceof OrgProducerDistributor){
                org = org65;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
        }
        
    }//GEN-LAST:event_sendToSupplierJButtonActionPerformed

    private void FrwdToWarehouseBRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrwdToWarehouseBRNActionPerformed
        // TODO add your handling code here:
        int scltRw3 = workRequestRMJTable.getSelectedRow();

        if (scltRw3 < 0){
            JOptionPane.showMessageDialog(null,"Please select a row before proceeding");
        }

        else{
        YieldRequest rqe = (YieldRequest)workRequestRMJTable.getValueAt(scltRw3, 0);
        rqe.setStatus("Forwarded to warehouse");
        populateSuppRequestTable();
        userAccount.getWorkQueue().getWorkRequestList().add(rqe);

        Organization org = null;
        for (Organization org32 : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (org32 instanceof OrgProducerWH){
                org = org32;
                break;
            }
           
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(rqe);
        }
        }
    }//GEN-LAST:event_FrwdToWarehouseBRNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FrwdFarmerBTN;
    private javax.swing.JButton FrwdToWarehouseBRN;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel valLbl;
    private javax.swing.JTable workRequestRMJTable;
    // End of variables declaration//GEN-END:variables
}
