
package UI.SystemAdminWorkArea;

import Model.EcoSys;
import Model.Enterprise.Enterprise;
import Model.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @Author Deshna, Dhir, Prasad, Anisha
 */
public class AdministerEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSys system;

       /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
    public AdministerEnterpriseJPanel(JPanel userProcessContainer, EcoSys system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateComboBox();
    }
   /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                //for looping
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                
                //test
                row[1] = network.getName();
                row[2] = enterprise.getEnterpriseType().getValue();

                   /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
                
                model.addRow(row);
            }
        }
    }

    private void populateComboBox() {
        ntwrkJComboBox.removeAllItems();
        enterpriseTypeJComboBox.removeAllItems();

        for (Network network : system.getNetworkList()) {
            ntwrkJComboBox.addItem(network);
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            enterpriseTypeJComboBox.addItem(type);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel144 = new javax.swing.JLabel();
        ntwrkJComboBox = new javax.swing.JComboBox();
        jLabel245 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enterpriseTypeJComboBox = new javax.swing.JComboBox();
        SBTJButton = new javax.swing.JButton();
        bkJButton = new javax.swing.JButton();
        jLabel445 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseJTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 570, 245));

        jLabel144.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel144.setText("Network");
        add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, 30));

        ntwrkJComboBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ntwrkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(ntwrkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 360, 370, -1));

        jLabel245.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel245.setText("Enterprise Name");
        add(jLabel245, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 482, -1, 30));

        nameText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 480, 370, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Enterprise Type");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, 30));

        enterpriseTypeJComboBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        enterpriseTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseTypeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 420, 370, -1));

        SBTJButton.setBackground(new java.awt.Color(51, 255, 255));
        SBTJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SBTJButton.setText("Submit");
        SBTJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SBTJButtonActionPerformed(evt);
            }
        });
        add(SBTJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 218, -1));

        bkJButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bkJButton.setText("Back");
        bkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkJButtonActionPerformed(evt);
            }
        });
        add(bkJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 120, 50));

        jLabel445.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel445.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel445.setText("Manage Enterprise");
        add(jLabel445, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 380, 59));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ModelSystemAdminWorkArea.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 1000, 870));
    }// </editor-fold>//GEN-END:initComponents

    private void SBTJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SBTJButtonActionPerformed
        if (nameText.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Kindly enter Enterprise name!");
        }
        else
        {
        Network network = (Network) ntwrkJComboBox.getSelectedItem();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) enterpriseTypeJComboBox.getSelectedItem();

        if (network == null || type == null) {
            JOptionPane.showMessageDialog(null, "Incorrect Input");
            return;
        }

        String name = nameText.getText();

        Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);

        populateTable();
        }
        nameText.setText("");
    }//GEN-LAST:event_SBTJButtonActionPerformed

    private void bkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkJButtonActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_bkJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SBTJButton;
    private javax.swing.JButton bkJButton;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JComboBox enterpriseTypeJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel245;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel445;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameText;
    private javax.swing.JComboBox ntwrkJComboBox;
    // End of variables declaration//GEN-END:variables
}
