
package UI.SystemAdminWorkArea;

import Model.EcoSys;
import Model.Enterprise.Enterprise;
import Model.Network.Network;
import Model.Organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @Author Deshna, Dhir, Prasad, Anisha
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

       /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
    JPanel userProcessContainer;
    EcoSys ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSys ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngNtwrk = new javax.swing.JButton();
        btnMngeEnterprise = new javax.swing.JButton();
        btnMngeAdmin = new javax.swing.JButton();
        jLabel133 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMngNtwrk.setBackground(new java.awt.Color(102, 255, 255));
        btnMngNtwrk.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnMngNtwrk.setText("Manage Network");
        btnMngNtwrk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngNtwrkActionPerformed(evt);
            }
        });
        add(btnMngNtwrk, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 330, -1));

        btnMngeEnterprise.setBackground(new java.awt.Color(102, 255, 255));
        btnMngeEnterprise.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnMngeEnterprise.setText("Manage Enterprise");
        btnMngeEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngeEnterpriseActionPerformed(evt);
            }
        });
        add(btnMngeEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 330, -1));

        btnMngeAdmin.setBackground(new java.awt.Color(51, 255, 255));
        btnMngeAdmin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnMngeAdmin.setText("Manage Enterprise Admin");
        btnMngeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngeAdminActionPerformed(evt);
            }
        });
        add(btnMngeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        jLabel133.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel133.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel133.setText("System Administrator");
        add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 600, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ModelSystemAdminWorkArea.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -190, 1020, 1120));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngeEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngeEnterpriseActionPerformed
        // TODO add your handling code here:
        AdministerEnterpriseJPanel manageEnterpriseJPanel=new AdministerEnterpriseJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageEnterpriseJPanel",manageEnterpriseJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngeEnterpriseActionPerformed
   /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/
    private void btnMngNtwrkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngNtwrkActionPerformed
        // TODO add your handling code here:
        AdministerNetworkJPanel manageNetworkJPanel=new AdministerNetworkJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngNtwrkActionPerformed

    private void btnMngeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngeAdminActionPerformed
        // TODO add your handling code here:
        AdministerEnterpriseAdminJPanel manageEnterpriseAdminJPanel=new AdministerEnterpriseAdminJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageEnterpriseAdminJPanel",manageEnterpriseAdminJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngeAdminActionPerformed
   /**
     * 
     * /*submit the inputs and wait the output

creates new panel for new role in the organization

data to be defined.

data passed in the function.

*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngNtwrk;
    private javax.swing.JButton btnMngeAdmin;
    private javax.swing.JButton btnMngeEnterprise;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel133;
    // End of variables declaration//GEN-END:variables
}
